"use client";

import { Database, Radio } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { DataSource } from "./types";

/**
 * Says plainly where the prices on screen came from.
 *
 * The dashboard runs on a deterministic price simulator whenever a live
 * provider is unreachable. That is fine for demoing the analysis, but the
 * numbers must never be mistaken for real quotes — so every surface that shows
 * prices carries this badge.
 */
export function DataSourceBadge({
  source,
  className,
}: {
  source: DataSource | undefined;
  className?: string;
}) {
  if (!source) return null;

  if (source === "live") {
    return (
      <Badge
        variant="outline"
        className={cn("gap-1 border-gain/40 bg-gain/10 text-gain text-[10px]", className)}
        title="Prices fetched from the live market-data provider"
      >
        <Radio className="h-3 w-3" /> Live data
      </Badge>
    );
  }

  return (
    <Badge
      variant="outline"
      className={cn("gap-1 border-warn/40 bg-warn/10 text-warn text-[10px]", className)}
      title="No live provider reachable — prices are generated by the deterministic simulator and are NOT real quotes"
    >
      <Database className="h-3 w-3" /> Simulated prices
    </Badge>
  );
}
